# Generated by Django 3.0.4 on 2020-03-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='group_id',
            new_name='group',
        ),
    ]
