# Generated by Django 3.0.4 on 2020-03-12 16:15

import apps.staff.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200312_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='working_type_id',
            field=models.CharField(choices=[(apps.staff.constants.WorkingType['FULL_TIME'], 'Full_Time'), (apps.staff.constants.WorkingType['PART_TIME'], 'Part_Time')], max_length=60),
        ),
    ]
