# Generated by Django 3.0.4 on 2020-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200312_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
