# Generated by Django 3.0.4 on 2020-03-13 01:52

import apps.staff.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200312_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='working_type_id',
            field=models.CharField(choices=[(apps.staff.constants.WorkingType['FULL_TIME'], 'Full Time'), (apps.staff.constants.WorkingType['PART_TIME'], 'Part Time')], default='Full Time', max_length=60),
        ),
    ]
