# Generated by Django 3.0.4 on 2020-03-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200312_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='group',
            new_name='group_id',
        ),
    ]
