# Generated by Django 3.0.4 on 2020-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200312_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developertype',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='developertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
