# Generated by Django 3.0.4 on 2020-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200312_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
