# Generated by Django 3.0.3 on 2020-03-11 04:00

import apps.project.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=254)),
                ('project_type_id', models.IntegerField(choices=[(apps.project.constants.ProjectType['DOMESTIC'], 'Domestic'), (apps.project.constants.ProjectType['INTERNATIONAL'], 'International')])),
                ('status', models.IntegerField(choices=[(apps.project.constants.StatusType['CANCELED'], 'Canceled'), (apps.project.constants.StatusType['COMPLETED'], 'Completed'), (apps.project.constants.StatusType['INITIALIZING'], 'Initializing'), (apps.project.constants.StatusType['INPROGRESS'], 'Inprogress'), (apps.project.constants.StatusType['NOT_STARTED'], 'Not Started'), (apps.project.constants.StatusType['PENDING'], 'Pending')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brse_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brse_staff', to='staff.Staffs')),
                ('comtor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comtor_staff', to='staff.Staffs')),
                ('leader_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_staff', to='staff.Staffs')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Partners')),
                ('team_leader_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_staff', to='staff.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('effort', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='PlanProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_effort', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
            ],
        ),
    ]
