version: '3.3'

services:
  database:
    container_name: mysql-prod
    image: mysql:5.7
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_manager
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    container_name: phpmyadmin-prod
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    depends_on:
      - database
    ports:
      - "8088:80"
    restart: always

  web:
    container_name: web-prod
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
        - database
    restart: always