# Generated by Django 3.0.4 on 2020-03-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type_id', models.IntegerField(blank=True, choices=[(1, 'Domestic'), (2, 'International')])),
                ('status_id', models.IntegerField(blank=True, choices=[(1, 'Canceled'), (2, 'Completed'), (3, 'Initializing'), (4, 'Inprogress'), (5, 'Not Started'), (6, 'Pending')])),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brse', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brse_staff', to='staff.Staffs')),
                ('comtor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comtor_staff', to='staff.Staffs')),
                ('leader', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_staff', to='staff.Staffs')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Partners')),
                ('team_leader', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_staff', to='staff.Staffs')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='StaffProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('effort', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staffs')),
            ],
            options={
                'db_table': 'staff_projects',
            },
        ),
        migrations.CreateModel(
            name='PlanProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_effort', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
            ],
            options={
                'db_table': 'plan_projects',
            },
        ),
    ]
